USUARIOS

###
POST http://localhost:3000/api/usuarios HTTP/1.1
Content-Type: application/json

{
    "id": "3",
    "nombre": "Santiago",
    "correo": "santiago@gmail.com",
    "contraseña": "920091",
    "fecha": "2023-09-12",
    "rol": "Dios"
}

###
GET http://localhost:3000/api/usuarios HTTP/1.1

###
GET http://localhost:3000/api/usuarios/650003f622705f07ad27c05f HTTP/1.1

###
PUT http://localhost:3000/api/usuarios/65000613d5bb5925227585ed HTTP/1.1
Content-Type: application/json

{
    "nombre": "david",
    "correo": "david@gmail.com",
    "contraseña": "tussi930",
    "fecha": "2023-09-12",
    "rol": "cachorro"
}

###
DELETE http://localhost:3000/api/usuarios/65000881b8a2c2f01bb63d84 HTTP/1.1

###
------------------------------------------------------------
ROLES

###
POST http://localhost:3000/api/roles HTTP/1.1
Content-Type: application/json

{
    "id": "2",
    "nombre": "prueba",
    "productos": false,
    "ventas": true,
    "compras": false,
    "proveedores": false
}

###
GET http://localhost:3000/api/roles HTTP/1.1

###
GET http://localhost:3000/api/roles/650237123eda61c051382ff3 HTTP/1.1

###
PUT http://localhost:3000/api/roles/650237313eda61c051382ff7 HTTP/1.1
Content-Type: application/json

{
    "id": "4",
    "nombre": "Empleado 2",
    "productos": true,
    "ventas": false,
    "compras": false,
    "proveedores": true
}

###
DELETE http://localhost:3000/api/roles/650237313eda61c051382ff7 HTTP/1.1